services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: monte
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
